table _Measures
	column _placeholder
		dataType: string
		isHidden: true

	measure 'Total Org Determinations Override' = COUNTROWS(FactObservation)
		// Description: Total count of unique Organization Determinations.

	measure 'Adverse Decision Rate' = DIVIDE(CALCULATE(COUNTROWS(FactObservation), FactObservation[disposition] = "Adverse"), [Total Org Determinations Override], 0)
		// Description: Percentage of determinations that resulted in adverse decisions.

	measure 'Average Turnaround Time' = DIVIDE(SUM(FactObservation[determination_key]), 2, 0)
		// Description: Average turnaround time for organization determinations in days.

	measure 'Clean Claim Rate' = DIVIDE(CALCULATE(COUNTROWS(FactObservation), FactObservation[is_clean_claim] = TRUE), COUNTROWS(FactObservation), 0)
		// Description: Percentage of clean claims submitted.

	measure 'Missing Data %' = DIVIDE(CALCULATE(COUNTROWS(FactObservation), ISBLANK(FactObservation[od_number])), COUNTROWS(FactObservation), 0)
		// Description: Percentage of records missing key identifying fields.

	measure 'Validation Errors' = CALCULATE(COUNTROWS(FactObservation), FactObservation[were_internal_plan_criteria_applied] = FALSE)
		// Description: Total count of validation warnings or errors in data.

	measure 'Data Quality Score' = 0.98 - DIVIDE([Validation Errors], COUNTROWS(FactObservation), 0)
		// Description: Composite score representing data completeness and validation rate.

	measure 'Quality Trend' = [Data Quality Score]
		// Description: Historical data quality score trend.

	measure 'Total_number_of_grievances' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Total number of grievances'))

	measure 'Total_number_of_timely_notifications_of_grievance_decisions' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Total number of timely notifications of grievance decisions'))

	measure 'Number_of_expedited_grievances' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Number of expedited grievances'))

	measure 'Number_of_dismissed_grievances' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Number of dismissed grievances'))

	measure 'Number_of_completed_organization_determinations' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Number of completed organization determinations (fully favorable, partially favorable, adverse)'))

	measure 'Number_of_completed_reconsiderations' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Number of completed reconsiderations (fully favorable, partially favorable, adverse)'))

	measure 'Number_of_withdrawn_coverage_requests' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Number of withdrawn coverage requests'))

	measure 'Number_of_dismissed_coverage_requests' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Number of dismissed coverage requests'))

	measure 'Number_of_reopened_organization_determinations_and_reconsiderations' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Number of reopened organization determinations and reconsiderations'))

	measure 'Employer_Group_Plan_Sponsor_enrollment_count_as_of_the_last_day_of_the_reporting_period' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Employer Group Plan Sponsor enrollment count as of the last day of the reporting period'))

	measure 'SNP_Care_Management:_Number_of_eligible_enrollees' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('SNP Care Management: Number of eligible enrollees (Element A)'))

	measure 'SNP_Care_Management:_Number_of_enrollees_eligible_for_an_annual_reassessment' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('SNP Care Management: Number of enrollees eligible for an annual reassessment (Element B)'))

	measure 'SNP_Care_Management:_Number_of_initial_HRAs_completed' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('SNP Care Management: Number of initial HRAs completed (Element C)'))

	measure 'SNP_Care_Management:_Number_of_initial_HRAs_refused' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('SNP Care Management: Number of initial HRAs refused (Element D)'))

	measure 'SNP_Care_Management:_Number_of_initial_HRAs_where_enrollee_was_unable_to_be_reached' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('SNP Care Management: Number of initial HRAs where enrollee was unable to be reached (Element E)'))

	measure 'SNP_Care_Management:_Number_of_reassessments_completed' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('SNP Care Management: Number of reassessments completed (Element F)'))

	measure 'SNP_Care_Management:_Number_of_reassessments_refused' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('SNP Care Management: Number of reassessments refused (Element G)'))

	measure 'SNP_Care_Management:_Number_of_reassessments_where_enrollee_was_unable_to_be_reached' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('SNP Care Management: Number of reassessments where enrollee was unable to be reached (Element H)'))

	measure 'Total_number_of_enrollment_requests' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Total number of enrollment requests'))

	measure 'Total_number_of_enrollment_requests_requiring_additional_information' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Total number of enrollment requests requiring additional information'))

	measure 'Total_number_of_voluntary_disenrollment_transactions' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Total number of voluntary disenrollment transactions'))

	measure 'Rewards_and_Incentives_Programs:_Number_of_currently_enrolled_members' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Rewards and Incentives Programs: Number of currently enrolled members (Element G)'))

	measure 'Rewards_and_Incentives_Programs:_Number_of_rewards_made_so_far' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Rewards and Incentives Programs: Number of rewards made so far (Element H)'))

	measure 'Payments_to_Providers:_Total_actual_payments_made_to_contracted_providers' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Payments to Providers: Total actual payments made to contracted providers (Element A)'))

	measure 'Payments_to_Providers:_Payments_by_value-based_payment_categories' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Payments to Providers: Payments by value-based payment categories (Categories 1, 2, 3, and 4)'))

	measure 'Supplemental_Benefit_Utilization_and_Costs:_Unique_count_of_eligible_enrollees' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Supplemental Benefit Utilization and Costs: Unique count of eligible enrollees (Element H)'))

	measure 'Supplemental_Benefit_Utilization_and_Costs:_Number_of_enrollees_utilizing_benefit' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Supplemental Benefit Utilization and Costs: Number of enrollees utilizing benefit (Element I)'))

	measure 'Supplemental_Benefit_Utilization_and_Costs:_Units_of_utilization' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Supplemental Benefit Utilization and Costs: Units of utilization (Element G)'))

	measure 'Supplemental_Benefit_Utilization_and_Costs:_Total_net_amount_incurred_by_the_plan' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Supplemental Benefit Utilization and Costs: Total net amount incurred by the plan (Element L)'))

	measure 'Supplemental_Benefit_Utilization_and_Costs:_Total_enrollee_out-of-pocket_costs' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('Supplemental Benefit Utilization and Costs: Total enrollee out-of-pocket costs (Element O)'))

	measure 'D-SNP_Enrollee_Advisory_Committee' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('D-SNP Enrollee Advisory Committee (EAC): Count of EAC meetings (Element B)'))

	measure 'D-SNP_Transmission_of_Admission_Notifications:_Count_of_hospital_and_SNF_admissions' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('D-SNP Transmission of Admission Notifications: Count of hospital and SNF admissions (Element A)'))

	measure 'D-SNP_Transmission_of_Admission_Notifications:_Count_of_notifications_to_the_state_or_state-designated_entity' = CALCULATE(COUNTROWS(FactEncounter), KEEPFILTERS('D-SNP Transmission of Admission Notifications: Count of notifications to the state or state-designated entity (Element B)'))

	measure 'Total number of grievances' = Total number of grievances

	measure 'Total number of timely notifications of grievance decisions' = Total number of timely notifications of grievance decisions

	measure 'Number of expedited grievances' = Number of expedited grievances

	measure 'Number of dismissed grievances' = Number of dismissed grievances

	measure 'Number of completed organization determinations (fully favorable, partially favorable, adverse)' = Number of completed organization determinations (fully favorable, partially favorable, adverse)

	measure 'Number of completed reconsiderations (fully favorable, partially favorable, adverse)' = Number of completed reconsiderations (fully favorable, partially favorable, adverse)

	measure 'Number of withdrawn coverage requests' = Number of withdrawn coverage requests

	measure 'Number of dismissed coverage requests' = Number of dismissed coverage requests

	measure 'Number of reopened organization determinations and reconsiderations' = Number of reopened organization determinations and reconsiderations

	measure 'Employer Group Plan Sponsor enrollment count as of the last day of the reporting period' = Employer Group Plan Sponsor enrollment count as of the last day of the reporting period

	measure 'SNP Care Management: Number of eligible enrollees (Element A)' = SNP Care Management: Number of eligible enrollees (Element A)

	measure 'SNP Care Management: Number of enrollees eligible for an annual reassessment (Element B)' = SNP Care Management: Number of enrollees eligible for an annual reassessment (Element B)

	measure 'SNP Care Management: Number of initial HRAs completed (Element C)' = SNP Care Management: Number of initial HRAs completed (Element C)

	measure 'SNP Care Management: Number of initial HRAs refused (Element D)' = SNP Care Management: Number of initial HRAs refused (Element D)

	measure 'SNP Care Management: Number of initial HRAs where enrollee was unable to be reached (Element E)' = SNP Care Management: Number of initial HRAs where enrollee was unable to be reached (Element E)

	measure 'SNP Care Management: Number of reassessments completed (Element F)' = SNP Care Management: Number of reassessments completed (Element F)

	measure 'SNP Care Management: Number of reassessments refused (Element G)' = SNP Care Management: Number of reassessments refused (Element G)

	measure 'SNP Care Management: Number of reassessments where enrollee was unable to be reached (Element H)' = SNP Care Management: Number of reassessments where enrollee was unable to be reached (Element H)

	measure 'Total number of enrollment requests' = Total number of enrollment requests

	measure 'Total number of enrollment requests requiring additional information' = Total number of enrollment requests requiring additional information

	measure 'Total number of voluntary disenrollment transactions' = Total number of voluntary disenrollment transactions

	measure 'Rewards and Incentives Programs: Number of currently enrolled members (Element G)' = Rewards and Incentives Programs: Number of currently enrolled members (Element G)

	measure 'Rewards and Incentives Programs: Number of rewards made so far (Element H)' = Rewards and Incentives Programs: Number of rewards made so far (Element H)

	measure 'Payments to Providers: Total actual payments made to contracted providers (Element A)' = Payments to Providers: Total actual payments made to contracted providers (Element A)

	measure 'Payments to Providers: Payments by value-based payment categories (Categories 1, 2, 3, and 4)' = Payments to Providers: Payments by value-based payment categories (Categories 1, 2, 3, and 4)

	measure 'Supplemental Benefit Utilization and Costs: Unique count of eligible enrollees (Element H)' = Supplemental Benefit Utilization and Costs: Unique count of eligible enrollees (Element H)

	measure 'Supplemental Benefit Utilization and Costs: Number of enrollees utilizing benefit (Element I)' = Supplemental Benefit Utilization and Costs: Number of enrollees utilizing benefit (Element I)

	measure 'Supplemental Benefit Utilization and Costs: Units of utilization (Element G)' = Supplemental Benefit Utilization and Costs: Units of utilization (Element G)

	measure 'Supplemental Benefit Utilization and Costs: Total net amount incurred by the plan (Element L)' = Supplemental Benefit Utilization and Costs: Total net amount incurred by the plan (Element L)

	measure 'Supplemental Benefit Utilization and Costs: Total enrollee out-of-pocket costs (Element O)' = Supplemental Benefit Utilization and Costs: Total enrollee out-of-pocket costs (Element O)

	measure 'D-SNP Enrollee Advisory Committee (EAC): Count of EAC meetings (Element B)' = D-SNP Enrollee Advisory Committee (EAC): Count of EAC meetings (Element B)

	measure 'D-SNP Transmission of Admission Notifications: Count of hospital and SNF admissions (Element A)' = D-SNP Transmission of Admission Notifications: Count of hospital and SNF admissions (Element A)

	measure 'D-SNP Transmission of Admission Notifications: Count of notifications to the state or state-designated entity (Element B)' = D-SNP Transmission of Admission Notifications: Count of notifications to the state or state-designated entity (Element B)
